# Generated by Django 5.0.3 on 2024-03-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djourneys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='discription',
            new_name='description',
        ),
    ]
