# Generated by Django 5.0.3 on 2024-03-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djourneys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
