# Generated by Django 5.0.3 on 2024-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djourneys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
