# Generated by Django 5.0.3 on 2024-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no city name', max_length=100)),
                ('state', models.CharField(default='no state name', max_length=100)),
                ('year_founded', models.CharField(default='no year found', max_length=100)),
                ('city_img', models.TextField(default='no image url', max_length=300, null=True)),
            ],
        ),
    ]
