# Generated by Django 5.0.3 on 2024-03-21 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no decade name', max_length=100)),
                ('description', models.TextField(default='no description', max_length=500)),
                ('attraction_img', models.CharField(default='no attraction image', max_length=250)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction', to='cities.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5)),
                ('guest_photo', models.ImageField(blank=True, null=True, upload_to='guest_photos/')),
                ('description', models.CharField(default='no description', max_length=250)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='cities.attraction')),
            ],
        ),
    ]
