# Generated by Django 4.2.11 on 2024-03-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Citie',
        ),
    ]
