# Generated by Django 4.2.11 on 2024-03-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_rename_city_citie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='city',
            new_name='citie',
        ),
    ]
