# Generated by Django 5.0.3 on 2024-03-21 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djourney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='attraction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='djourney.attraction'),
        ),
    ]
