# Generated by Django 3.2.12 on 2024-03-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djourney', '0002_review_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('None', 'None'), ('X', 'X'), ('XX', 'XX'), ('XXX', 'XXX'), ('XXXX', 'XXXX'), ('XXXXX', 'XXXXX')], default='None', max_length=10),
        ),
    ]
