# Generated by Django 5.0.3 on 2024-03-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='city.attraction'),
        ),
    ]
